DO NOT MERGE: try bumping eksctl and kubectl
hitting the:
  error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"
issue, which seems to be due to kubeconfig specifying wrong api version.

Trying to bump both kubectl and eksctl to newer version to see if they'd
generate the right kubeconfig in order for helm to work.

Signed-off-by: Jussi Maki <jussi@isovalent.com>